version: '3'

services:
    gunicorn:
        build: .
        image: gunicorn:20.1.0
        container_name: gunicorn
        volumes:
            - .:/usr/src/app/
            - gunicorn:/var/run/gunicorn
        env_file: docker.env
volumes:
    gunicorn:
        driver: local
