version: '3'

services:
    db:
        image: postgres
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=password"

    gunicorn:
        build: .
        restart: always
        image: gunicorn:20.1.0
        container_name: gunicorn
        volumes:
            - .:/usr/src/app/
            - gunicorn:/var/run/gunicorn
    nginx:
        restart: always
        image: nginx:1.17.7
        container_name: nginx
        depends_on:
            - gunicorn
        ports:
            - "80:80"
        volumes:
            - ./gunicorn.conf:/etc/nginx/conf.d/default.conf
            - gunicorn:/var/run/gunicorn
            - ./static:/usr/src/app/static
            - ./images:/usr/src/app/images
volumes:
    gunicorn:
        driver: local
