version: '3'

services:
    db:
        image: postgres
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=password"

    gunicorn:
        build: .
        restart: always
        image: gunicorn:20.1.0
        container_name: gunicorn
        depends_on:
            - db
        volumes:
            - .:/usr/src/app/
            - gunicorn:/var/run/gunicorn

volumes:
    gunicorn:
        driver: local
